name: rmsfinder_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - numpy
  - pandas
  - python=3.8
  - biopython
  - hmmer
  - blast
#  - tqdm
  - python-wget
# - ncbi-genome-download (only if want to download refseq)
